apiVersion: v1
kind: Service
metadata:
  name: netology-app-nodeport
spec:
  type: NodePort
  selector:
    app: netology-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
