version: "3.9"

services:
  db:
    image: mysql:8.0.33
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    ports:
      - "3306:3306"

volumes:
  db_data: