web:
  image:
    repository: "nginx"
    tag: "1.20"
  replicas: 2

db:
  image:
    repository: "postgres"
    tag: "14"
  replicas: 1
  env:
    POSTGRES_DB: "mydatabase"
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "mypassword"
