version: "3.9"

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_backup:/backup
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

volumes:
  db_data:
  db_backup:
