---
# - name: Install Clickhouse
#   hosts: clickhouse
#   tags: clickhouse
#   roles:
#     - clickhouse
- name: Install Vector
  hosts: vector
  become: true
  tags: vector
  roles:
    - vector
# - name: Install lighthouse
#   hosts: lighthouse
#   become: true
#   tags: lighthouse
#     - lighthouse
