---
# tasks file for lighthouse
- name: Intsall epel-release
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
- name: Intsall nginx
  become: true
  ansible.builtin.dnf:
    name: nginx
    state: present
  notify: Started nginx
- name: Configure nginx
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Start reloaded
- name: Install git
  become: true
  ansible.builtin.dnf:
    name: git
    state: present
- name: Get ligthhouse repo
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_dir }}"
- name: Configure lighthouse
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: "0644"
  notify: Start reloaded