apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool
          command:
            [
              "/bin/sh",
              "-c",
              "while true; do date >> /mnt/data/sharedfile; sleep 5; done",
            ]
          volumeMounts:
            - name: nfs-storage
              mountPath: /mnt/data
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
