stages:
  - build
  - deploy
  - test

image: docker:24.0.5
services:
  - name: docker:24.0.5-dind

# before_script:
#     - docker info

build image:
  stage: build
  script:
    - echo $CI_PROJECT_NAME
    - docker build -t $CI_PROJECT_NAME:latest .
  except:
    - main
    - master

deploy to registry:
  stage: deploy
  script:
    - echo $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest
  only:
    - main
    - master

test latest build:
  image: curlimages/curl
  services:
    - name: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest
      alias: python-api
  stage: test
  script:
    - curl -ss http://python-api:5290/get_info | grep Running
  only:
    - main
    - master
